"""QuantPulse v3 - All Pydantic models for inter-agent communication."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field

from .enums import (
    Priority, Direction, AgentRole, OrderStatus, OrderType,
    MarketRegime, Timeframe, AlertSeverity, TradeMode,
)


# ──────────────────────────────────────────────
# MessageBus Core
# ──────────────────────────────────────────────

class Message(BaseModel):
    """Universal message envelope for MessageBus."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:16])
    topic: str
    sender: AgentRole
    priority: Priority = Priority.NORMAL
    payload: dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    correlation_id: str | None = None  # For request-response patterns


# ──────────────────────────────────────────────
# MIA Models
# ──────────────────────────────────────────────

class MarketStructureReport(BaseModel):
    """SMC/ICT market structure analysis."""
    symbol: str
    timeframe: Timeframe
    regime: MarketRegime
    trend_direction: Direction
    trend_strength: float = Field(ge=0.0, le=1.0)
    key_levels: list[float] = Field(default_factory=list)
    order_blocks: list[dict[str, Any]] = Field(default_factory=list)
    fair_value_gaps: list[dict[str, Any]] = Field(default_factory=list)
    liquidity_zones: list[dict[str, Any]] = Field(default_factory=list)
    break_of_structure: bool = False
    change_of_character: bool = False
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TimeframeAnalysis(BaseModel):
    """Analysis for a single timeframe."""
    timeframe: Timeframe
    structure: MarketStructureReport
    bias: Direction
    confidence: float = Field(ge=0.0, le=1.0)


class MultiTimeframeAnalysis(BaseModel):
    """Combined multi-timeframe analysis from MIA."""
    symbol: str
    analyses: list[TimeframeAnalysis] = Field(default_factory=list)
    htf_bias: Direction  # Higher timeframe bias
    ltf_confirmation: bool = False  # Lower timeframe confirms
    confluence_score: float = Field(ge=0.0, le=1.0)
    regime: MarketRegime
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TradeSignal(BaseModel):
    """Trade signal generated by MIA."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    symbol: str
    direction: Direction
    score: float = Field(ge=0.0, le=100.0)
    entry_price: float
    stop_loss: float
    take_profit_1: float
    take_profit_2: float | None = None
    take_profit_3: float | None = None
    timeframe: Timeframe
    regime: MarketRegime
    analysis_summary: str = ""
    confluence_factors: list[str] = Field(default_factory=list)
    risk_reward_ratio: float = Field(ge=0.0)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ──────────────────────────────────────────────
# QR Models
# ──────────────────────────────────────────────

class QuantScore(BaseModel):
    """Quantitative scoring from QR agent (8 dimensions)."""
    signal_id: str
    symbol: str
    # 8 scoring dimensions (0-100 each)
    trend_alignment: float = Field(ge=0.0, le=100.0)
    momentum_score: float = Field(ge=0.0, le=100.0)
    volume_profile: float = Field(ge=0.0, le=100.0)
    volatility_regime: float = Field(ge=0.0, le=100.0)
    orderflow_imbalance: float = Field(ge=0.0, le=100.0)
    correlation_filter: float = Field(ge=0.0, le=100.0)
    statistical_edge: float = Field(ge=0.0, le=100.0)
    timing_score: float = Field(ge=0.0, le=100.0)
    # Aggregated
    total_score: float = Field(ge=0.0, le=100.0)
    grade: str  # A+, A, B+, B, C, D, F
    reasons: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def compute_total(self) -> float:
        weights = {
            "trend_alignment": 0.20,
            "momentum_score": 0.15,
            "volume_profile": 0.10,
            "volatility_regime": 0.10,
            "orderflow_imbalance": 0.15,
            "correlation_filter": 0.10,
            "statistical_edge": 0.10,
            "timing_score": 0.10,
        }
        total = sum(
            getattr(self, dim) * w for dim, w in weights.items()
        )
        self.total_score = round(total, 2)
        return self.total_score

    def compute_grade(self) -> str:
        s = self.total_score
        if s >= 90: self.grade = "A+"
        elif s >= 80: self.grade = "A"
        elif s >= 70: self.grade = "B+"
        elif s >= 60: self.grade = "B"
        elif s >= 50: self.grade = "C"
        elif s >= 40: self.grade = "D"
        else: self.grade = "F"
        return self.grade


# ──────────────────────────────────────────────
# CRCO Models
# ──────────────────────────────────────────────

class RiskValidation(BaseModel):
    """Single risk check result."""
    check_name: str
    passed: bool
    value: float | None = None
    threshold: float | None = None
    detail: str = ""


class RiskAssessment(BaseModel):
    """Full risk assessment from CRCO."""
    signal_id: str
    symbol: str
    approved: bool
    validations: list[RiskValidation] = Field(default_factory=list)
    veto_reasons: list[str] = Field(default_factory=list)
    risk_score: float = Field(ge=0.0, le=100.0, default=0.0)
    max_position_size: float = 0.0
    recommended_leverage: float = 1.0
    circuit_breaker_active: bool = False
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def vetoed(self) -> bool:
        return not self.approved


# ──────────────────────────────────────────────
# CSO Models
# ──────────────────────────────────────────────

class TradeDecision(BaseModel):
    """Final trade decision from CSO (only if CRCO approved)."""
    decision_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    signal_id: str
    symbol: str
    direction: Direction
    approved: bool
    entry_price: float
    stop_loss: float
    take_profit_1: float
    take_profit_2: float | None = None
    take_profit_3: float | None = None
    position_size: float
    leverage: float = 1.0
    order_type: OrderType = OrderType.LIMIT
    trade_mode: TradeMode = TradeMode.PAPER
    quant_score: float = 0.0
    quant_grade: str = ""
    risk_score: float = 0.0
    reasoning: str = ""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ──────────────────────────────────────────────
# ES Models
# ──────────────────────────────────────────────

class OrderResult(BaseModel):
    """Order execution result from ES."""
    order_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    decision_id: str
    signal_id: str
    symbol: str
    direction: Direction
    order_type: OrderType
    status: OrderStatus
    requested_price: float
    filled_price: float | None = None
    quantity: float
    filled_quantity: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0
    exchange: str = ""
    trade_mode: TradeMode = TradeMode.PAPER
    error_message: str = ""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TradeRecord(BaseModel):
    """Complete trade lifecycle record."""
    trade_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    signal_id: str
    symbol: str
    direction: Direction
    entry_price: float
    exit_price: float | None = None
    stop_loss: float
    take_profit_1: float
    quantity: float
    pnl: float = 0.0
    pnl_percent: float = 0.0
    commission_total: float = 0.0
    duration_seconds: int = 0
    trade_mode: TradeMode = TradeMode.PAPER
    opened_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    closed_at: datetime | None = None


# ──────────────────────────────────────────────
# PO Models
# ──────────────────────────────────────────────

class PerformanceReport(BaseModel):
    """Periodic performance report from PO."""
    report_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    period: str  # e.g. "daily", "weekly"
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    sharpe_ratio: float = 0.0
    profit_factor: float = 0.0
    avg_risk_reward: float = 0.0
    best_trade_pnl: float = 0.0
    worst_trade_pnl: float = 0.0
    avg_trade_duration_seconds: int = 0
    consecutive_wins: int = 0
    consecutive_losses: int = 0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ──────────────────────────────────────────────
# IMA Models
# ──────────────────────────────────────────────

class HealthStatus(BaseModel):
    """Agent health status for IMA monitoring."""
    agent: AgentRole
    alive: bool = True
    uptime_seconds: int = 0
    messages_processed: int = 0
    errors_count: int = 0
    last_heartbeat: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    memory_mb: float = 0.0
    cpu_percent: float = 0.0
    extra: dict[str, Any] = Field(default_factory=dict)


class AlertEvent(BaseModel):
    """Alert event from IMA."""
    alert_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    severity: AlertSeverity
    source: AgentRole
    title: str
    detail: str = ""
    acknowledged: bool = False
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ──────────────────────────────────────────────
# Audit Log Model
# ──────────────────────────────────────────────

class AuditEntry(BaseModel):
    """Single audit log entry."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:16])
    agent: AgentRole
    action: str
    detail: dict[str, Any] = Field(default_factory=dict)
    correlation_id: str | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
